### ISSUE TITLE
webpack babel package error

### ISSUE THREAD

**Issue by zhangwen9229** [TanNgocDo/Js-Amino#17]
![image](https://user-images.githubusercontent.com/5137377/48831666-4016d580-edb2-11e8-9e0f-24dc32ad0421.png)

**Comment by TanNgocDo** [comment]
Thanks, please check the update: https://github.com/TanNgocDo/Js-Amino/commit/3762c096f53534c3cd8186d9112023d588c8b2ea

**Comment by zhangwen9229** [comment]
![image](https://user-images.githubusercontent.com/5137377/48832648-9c7af480-edb4-11e8-91ef-dfdbf915023f.png)
something error else,let me check.

**Comment by TanNgocDo** [comment]
Which node version are you using ?

**Comment by zhangwen9229** [comment]
![image](https://user-images.githubusercontent.com/5137377/48832950-4e1a2580-edb5-11e8-9746-c25bc5d0d0bd.png)
delete plugin "transform-runtime" in .babelrc, the error is resolved.

**Comment by TanNgocDo** [comment]
Thanks, I have not checked with babel before

**Comment by zhangwen9229** [comment]
![image](https://user-images.githubusercontent.com/5137377/48833136-af41f900-edb5-11e8-82ee-8baf3d175de1.png)
This is the babel version which I have used. For reference only.

**Comment by zhangwen9229** [comment]
> Thanks, I have not checked with babel before

It was nice working with you.
