### ISSUE TITLE
Typo on field options

### ISSUE THREAD

**Issue by Thunnini** [TanNgocDo/Js-Amino#23]
https://github.com/TanNgocDo/Js-Amino/blob/master/src/codec.js#L28
this.binFixed64 = opts.binFixed64 || false; // (Binary) Encode as fixed64
this.binFix32 = opts.binFix32 || false; // (Binary) Encode as fixed32

What was your original intention of the two?
binFixed or binFix?

**Comment by TanNgocDo** [comment]
thanks, the typos was fixed
