### ISSUE TITLE
Converting type to typ3 with considering options.

### ISSUE THREAD

**Issue by Thunnini** [TanNgocDo/Js-Amino#24]
Currently, js-amino convert type to typ3 with considering only type.
So, when encoding int with bin-fixed option, js-amino can't get valid typ3.
So js-amino needs to consider options when converting type to typ3.

**Comment by TanNgocDo** [comment]
I have just sent you an invitation. Could you please check ?

**Comment by Thunnini** [comment]
I can assgin. Thank you!
