### ISSUE TITLE
Encoding of default values

### ISSUE THREAD

**Issue by litvintech** [TanNgocDo/Js-Amino#27]
Amino do not encode default value fields. For example don't encode empty string.
```
let Fee = TypeFactory.create('fee', [{
        name: 'amount',
        type: Types.ArrayStruct,
    },
    {
        name: 'gas',
        type: Types.Int64,
    }
]);
let Coin = TypeFactory.create('coin', [{
        name: 'denom',
        type: Types.String,
    },
    {
        name: 'amount',
        type: Types.String,
    }
]);
let fee = new Fee([new Coin('', '0')], 200000);
console.log("binary fee:\n ", codec.marshalBinary(fee));
```
```
got [ 11, 10, 5, 10, 0, 18, 1, 48, 16, 192, 154, 12 ] // js-amino
expected [9 10 3 18 1 48 16 192 154 12] // go-amino
```
If denom is not empty string everything works fine

**Comment by TanNgocDo** [comment]
Thanks, I forgot to check about the default value in encoding. Will notice and update it

**Comment by litvintech** [comment]
> Thanks, I forgot to check about the default value in encoding. Will notice and update it

Hi, I created the [PR 28](https://github.com/TanNgocDo/Js-Amino/pull/28), please check them

**Comment by TanNgocDo** [comment]
Thanks, I merge it. If ok, could you please close this issue ?
