### ISSUE TITLE
Need to provide unit test

### ISSUE THREAD

**Issue by TanNgocDo** [TanNgocDo/Js-Amino#3]

**Comment by ethanfrey** [comment]
Hi, thank you for starting work on this. I was happy to hear it existed and would be glad to use it.

The first two things I noticed were the lack of some unit tests, and lack of types (I am biased to Typescript, but that is not essential at all).

If you want, I could make a PR with a lot of test cases generated from golang, with hex-encoded binary format and unmarshalled structure. Let me know if that would be useful, and I will make a pr.  I don't have much time to work on this, but would love to support somehow.

**Comment by TanNgocDo** [comment]
Hi Ethan, I'm very happy if you can provide some test-cases. 
Typescript will be supported soon(I hope).
Due to the "dynamic typing" of JS, Js-Amino needs to provide an "intermediate" "AminoType" that contained declared types(Int8,Int64,String, Interface.....)  before actually encode/decode. 
Currently, I created 2 branches: master and "compatibility" .

- "Master"  keeps updated with the lasted version of Go-Amino(with v.0.10.1 of Go-Amino). I tested with some simple encode and decode, but not have implemented decode/encode with Interface from/to Go Interface. It will be added soon.

-  Branch  "compatibility" works with Go-Amino(v.0.9.9) . It has not had decoding feature yet(but works well with encoding ). I'm using this branch for encoding on my JS-client to encode Transaction and send to Cosmos to decode it. It's ok right now :) 
I will take one or two days to provide the documentation and refactor the code, I guest two branches will be developed independently.
  
Please feel free to add PR, I'm very happy to have comment and contribution.
