### ISSUE TITLE
Another amino library for javascript

### ISSUE THREAD

**Issue by Thunnini** [TanNgocDo/Js-Amino#48]
https://github.com/node-a-team/ts-amino
I'm not sure if I should post this here. I'm trying to create javascript library for Cosmos-SDK. And I prefer typescript that is fully compatible with javascript and supports type checking. I want to use modern javascript grammar and typescript features. So I wrote a new amino library from the ground up. The main difference is that this uses the decorator to define amino structure. I don't make decoding features yet. But I succeeded to send the transaction with my library.
If you want to use your library for sending the transactions on Cosmos-SDK, [this](https://github.com/node-a-team/cosmosjs) will help.
I hope we can compete in good faith.

**Comment by cyborgshead** [comment]
@Thunnini thanks for your contribution to cosmos ecosystem. We appreciate TypeScript too)
We going to think about a move to TS, thanks to mentioning your progress!
