### ISSUE TITLE
How to create slice of structs?

### ISSUE THREAD

**Issue by arturalbov** [TanNgocDo/Js-Amino#6]
Hello!
Is there any way to create slice of structs?
For example: 
I need `StdFee` type that looks like
```
StdFee {
    amount: []Coin,
    gas: Int64
}
```

How to define []Coin array?

**Comment by TanNgocDo** [comment]
Thanks for your question
I'm implement this feature. I will let you know when it's finish tomorrow

**Comment by arturalbov** [comment]
@TanNgocDo Cool! Thank you :)
Would be great if you upload your library to npm

**Comment by arturalbov** [comment]
Thank you very much 👍 I'll try it soon

**Comment by TanNgocDo** [comment]
You're welcome. Please feel free to raise issue or contact me if you have any concern

**Comment by TanNgocDo** [comment]
@arturalbov Have you tried it and feel it ok ? If so, I would like to close this issue

**Comment by arturalbov** [comment]
Yes, you could close it. Thanks!
